config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    get :download, on: :member
  end

  get '/' => 'tasks#new'
  root 'tasks#new'

  

end

app/models/task.rb
class Task < ActiveRecord::Base
	validates :url, presence: true
	validates_format_of :url, :with => URI::regexp(%w(http https))
	validates_format_of :url, with: /((\Syoutube.com\/(watch|playlist)?\?\S+=\S)|(\Syoutu.be\/\S))/, on: :create

	before_validation(on: :create) do
		self.url = "http://#{self.url}" unless self.url[/^https?/]
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
require 'zip'

class TasksController < ApplicationController
	def new
		@tasks = Task.all
	end

	def create
		@task = Task.new(task_params)
		@task.title = @task.url
		if @task.save
			Resque.enqueue(ConvertYoutubeJob, @task.id)
			redirect_to new_task_path
		else
			redirect_to new_task_path, :alert => @task.errors.empty? ? 'Something went wrong. Try again.' : @task.errors.full_messages.to_sentence
		end
	end

	def destroy
		@task = Task.find(params[:id])
		path = "#{Rails.root}/tmp/#{@task.download_url}"
		
		if @task.download_url != nil && File.exist?(path)
			File.delete(path)
		end
		@task.destroy

		redirect_to new_task_path
	end

	def download
		@task = Task.find(params[:id])
	    send_file "#{Rails.root}/tmp/#{@task.download_url}"
	end

	private
		def task_params
			params.require(:task).permit(:url, :done)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Convert Youtube</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper"><%= yield %></div>
</body>
</html>

app/views/tasks/new.html.erb
<% if flash[:alert] %>
	<div class="alert"><%= flash[:alert] %></div>
<% end %>

<%= form_for :task, url: tasks_path do |f| %>
	<%= f.text_field :url %>
	<%= f.submit 'Convert', :class => 'submit_button' %>
<% end %>

<% @tasks.each do |task| %>
	<p><%= task.title %>
		<% if task.done %>
			<% if task.failed %>
				<span class="status">Failed</span>
			<% else %>
				<%= link_to 'Download', download_task_path(task), :class => 'button' %>
			<% end %>
			
			
			<%= link_to 'Remove', task_path(task), :class => 'button',
					method: :delete,
					data: { confirm: 'Are you sure?' } %>
			<% else %>
				<span class="status">Processing</span>
			<% end %>
	</p>
<% end %>